import Blog from "./Blog";
import "./Blog.css"

export async function generateMetadata() {

    return {
        title: "Add Your Blog",
        description: "Generated by create next app",
        icons: {
            icon: "https://i.ibb.co/f9g36Zz/exploresphere-high-resolution-logo-transparent-1.png"
        }
    }
}


export default function AddBlog() {

    return (
        <section id="add_blog" className="relative">
            <div className="my-auto top-10 relative">
                <h1 id="title" className="text-4xl font-bold text-center my-auto mt-3 mb-5">Add Your Blog Post</h1>
                <Blog></Blog>
            </div>
        </section>
    );
}