import Blog from "./Blog";
import "./Blog.css"

export async function generateMetadata() {

    return {
        title: "Add Your Blog",
        description: "Generated by create next app",
    }
}


export default function AddBlog() {

    return (
        <section id="add_blog" className="bg-[#c0b2f3] relative  ">
            <div className="my-auto ">
                <h1 className="text-4xl font-bold text-center my-auto mb-3">Add Your Blog Post</h1>
                <Blog ></Blog>
            </div>
        </section>
    );
}